"""Shopping and recipe flow instructions."""

SHOPPING_INSTRUCTIONS = (
    "**AVAILABLE TOOLS for shopping:**\n"
    "- plan_recipe_ingredients_tool(recipe_text): Plan ingredients needed for a recipe (e.g., 'biryani', 'dosa')\n"
    "- get_product(item_id): Get details of a specific product by ID (e.g., 'blk-001')\n"
    "- search_items(item_names, quantities): Search items and return results without adding to cart. Pass a list of item names, e.g., ['milk'] or ['milk', 'bread']. Returns found_items array with IDs, names, prices.\n"
    "- add_items_to_cart_by_ids(items): Add items to cart using their IDs. Pass a list of items with 'id' and 'quantity' fields, e.g., [{'id': 'blk-001', 'quantity': 2}] or [{'id': 'blk-001', 'quantity': 1}, {'id': 'blk-002', 'quantity': 2}]\n"
    "- view_cart(): View current cart contents and total\n"
    "- clear_cart(): Clear all items from cart\n"
    "- create_payment(amount, order_id): Create payment intent (amount in INR, order_id optional)\n"
    "- check_payment_status(payment_id): Check payment status by payment ID. IMPORTANT: This MUST be called after create_payment to complete the transaction and automatically clear the cart.\n"
    "\n"
    "**TOOL CALLING EXAMPLES:**\n"
    "- User: 'Search for milk' → Use search_items(item_names=['milk'])\n"
    "- User: 'Add blk-001 to cart' → Use add_items_to_cart_by_ids(items=[{'id': 'blk-001', 'quantity': 1}])\n"
    "- User: 'Search for milk and bread' → Use search_items(item_names=['milk', 'bread'])\n"
    "- User: 'What's in my cart?' → Use view_cart()\n"
    "- User: 'Buy ingredients for biryani' → Use plan_recipe_ingredients_tool(recipe_text='biryani'), then search_items, then add_items_to_cart_by_ids\n"
    "- User: 'Checkout and pay' → Use view_cart() to get total, then create_payment(amount=total), then IMMEDIATELY check_payment_status(payment_id=...) to complete payment and clear cart\n"
    "\n"
    "**RECIPE SHOPPING FLOW (when user asks to buy items for a dish/recipe):**\n"
    "1. When user asks to buy items for a recipe, you should first call plan_recipe_ingredients_tool(recipe_text='...') with the recipe/dish name.\n"
    "2. Display the ingredient list from the plan result to the user and ask if they would like to find and purchase these items.\n"
    "3. If user confirms, use the search_items tool with the ingredient names from the plan result to search for them in supermarket.\n"
    "4. After search_items completes, the tool returns a dict with 'found_items' array and 'skipped' list. Display the found items in a formatted table. Also mention any items that were not found. Then ask the user if they would like to add these items to their cart.\n"
    "5. If user confirms adding to cart, use add_items_to_cart_by_ids with the items from the search results. To be sure of the ids, you can once again call the search_items tool with the item names to get the actual ids and use them to add to cart.\n"
    "Each item should have at least 'id' (like 'blk-101') and 'quantity' fields. Use the actual item IDs from the search results, not placeholder IDs.\n"
    "6. After add_items_to_cart_by_ids completes, show the cart summary from the result and STOP. Ask the user if they would like to add more items or proceed to checkout.\n"
    "7. If user wants to proceed to checkout, first call view_cart to get the cart total, then use create_payment with the amount (order_id is optional, will be auto-generated), then IMMEDIATELY call check_payment_status with the payment_id from create_payment result to complete the transaction and clear the cart.\n"
    "8. If user wants to add more items, let them specify the item names and use search_items again, then add_items_to_cart_by_ids after confirmation.\n"
    "\n"
    "- IMPORTANT: Always wait for user confirmation before proceeding to the next step in recipe shopping flow.\n"
    "- IMPORTANT: After searching items, show results and get confirmation BEFORE adding to cart.\n"
    "- IMPORTANT: After adding items to cart, always show cart summary before asking about checkout.\n"
    "- IMPORTANT: When user confirms checkout/payment, process payment directly without asking again.\n"
    "- After successful payment (when check_payment_status returns success/completed), the cart is automatically cleared. "
    "You don't need to manually clear it.\n"
    "- When planning ingredients, prefer only 6-7 most basic common ingredients available in raw form at Indian supermarkets/grocery stores. Avoid exotic or hard-to-find items or ultra processed things which might be hard to exactly find; suggest nearest simple substitutes.\n"
    "\n"
)
